### PR TITLE
made new branch and removed all sigma3 stuff

### PR DESCRIPTION
**Pull request by jwang-101**
I redid the sigma3 removal stuff. Hopefully there isn't merge conflicts this time... and hopefully I redid the stuff correctly too and didn't miss anything.

I tried running the frontend/backend locally and it seemed okay on the website and on beekeeper too 

- Justin

### CODE REVIEW

**Comment by jwang-101** [comment]
mmmn, i'm not sure why it's saying web is conflicting since i'm sure i branched it from main and i tried git in the web directory before branching..

**Review by bhutz — CHANGES_REQUESTED** [review]
There are two places with sigma_three is missed

line 372 in functions_helper
line 197 in families_helper

**Comment by jwang-101** [comment]
sorry for missing those! i've gone through and done that

**Review by bhutz — APPROVED** [review]
looks good

**Comment by bhutz** [comment]
fixes issue #11

**Pull request merged**
